"""empty message

Revision ID: 733cc687d08a
Revises: c41ec316092d
Create Date: 2023-02-15 10:44:41.533644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733cc687d08a'
down_revision = 'c41ec316092d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_decription', sa.String(length=120), nullable=True))
        batch_op.drop_column('seeking_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_decription')

    # ### end Alembic commands ###
