"""empty message

Revision ID: 79411f5be51a
Revises: 261b3c4c44da
Create Date: 2023-02-15 22:15:38.576375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79411f5be51a'
down_revision = '261b3c4c44da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artists', schema=None) as batch_op:
        batch_op.drop_column('website')

    # ### end Alembic commands ###
