"""empty message

Revision ID: 8207fb7b2277
Revises: 733cc687d08a
Create Date: 2023-02-15 10:48:01.296396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8207fb7b2277'
down_revision = '733cc687d08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=120), nullable=True))
        batch_op.drop_column('seeking_decription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_decription', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_description')

    # ### end Alembic commands ###
