"""empty message

Revision ID: bb9853459602
Revises: 7ff14605dadb
Create Date: 2023-02-14 17:52:20.701339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9853459602'
down_revision = '7ff14605dadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('seeking_venue_decription',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('seeking_talent_decription',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_talent_decription',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('seeking_venue_decription',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
